version: '2.2'
services:
  org-management:
    build: org-management
    image: org-management
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.org-management"
  user-management:
    build: user-management
    image: user-management
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.user-management"

  fluentd:
    depends_on:
      - elasticsearch
    build: ./fluentd/
    ports:
      - "24224:24224"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  elasticsearch:
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
